# Netlify configuration for VitePress documentation site

[build]
  # Build command
  command = "npm run docs:build"

  # Directory with the built site
  publish = "docs/.vitepress/dist"

  # Set Node.js version
  [build.environment]
    NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Deploy previews configuration
[context.deploy-preview]
  command = "npm run docs:build"

# Branch deploys
[context.branch-deploy]
  command = "npm run docs:build"
